/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/tablepcssnotex.gltf -k 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Pc(props) {
  const { nodes, materials } = useGLTF("/mainmodel.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        position={[0, 0.803, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group
          name="611662d5eb454635875e800d567d3ec6fbx"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <group
            name="casette_base_low002"
            position={[-6.496, -0.033, 1.768]}
            rotation={[-Math.PI, 1.282, Math.PI / 2]}
            scale={[1.054, 0.955, 0.996]}
          >
            <mesh
              name="casette_base_low002_M_Details_0"
              geometry={nodes.casette_base_low002_M_Details_0.geometry}
              material={materials.M_Details}
            />
            <mesh
              name="casette_base_low002_M_Details_Translucent_0"
              geometry={
                nodes.casette_base_low002_M_Details_Translucent_0.geometry
              }
              material={materials.M_Details_Translucent}
            />
          </group>
          <group
            name="casette_base_low003"
            position={[-6.539, 0.758, 1.633]}
            rotation={[-Math.PI, 1.282, Math.PI / 2]}
            scale={[1.054, 0.955, 0.996]}
          >
            <mesh
              name="casette_base_low003_M_Details_0"
              geometry={nodes.casette_base_low003_M_Details_0.geometry}
              material={materials.M_Details}
            />
            <mesh
              name="casette_base_low003_M_Details_Translucent_0"
              geometry={
                nodes.casette_base_low003_M_Details_Translucent_0.geometry
              }
              material={materials.M_Details_Translucent}
            />
          </group>
          <group
            name="casette_base_low004"
            position={[5.423, -0.033, -8.574]}
            rotation={[0, -0.652, -Math.PI / 2]}
            scale={[1.054, 0.955, 0.996]}
          >
            <mesh
              name="casette_base_low004_M_Details_0"
              geometry={nodes.casette_base_low004_M_Details_0.geometry}
              material={materials.M_Details}
            />
            <mesh
              name="casette_base_low004_M_Details_Translucent_0"
              geometry={
                nodes.casette_base_low004_M_Details_Translucent_0.geometry
              }
              material={materials.M_Details_Translucent}
            />
          </group>
          <group
            name="casette_base_low009"
            position={[5.376, 0.829, -8.55]}
            rotation={[0, -0.169, -Math.PI / 2]}
            scale={[1.054, 0.955, 0.996]}
          >
            <mesh
              name="casette_base_low009_M_Details_0"
              geometry={nodes.casette_base_low009_M_Details_0.geometry}
              material={materials.M_Details}
            />
            <mesh
              name="casette_base_low009_M_Details_Translucent_0"
              geometry={
                nodes.casette_base_low009_M_Details_Translucent_0.geometry
              }
              material={materials.M_Details_Translucent}
            />
          </group>
          <group
            name="casette_base_low010"
            position={[5.834, 0.1, 1.818]}
            rotation={[0, 1.504, -Math.PI / 2]}
            scale={[1.054, 0.955, 0.996]}
          >
            <mesh
              name="casette_base_low010_M_Details_0"
              geometry={nodes.casette_base_low010_M_Details_0.geometry}
              material={materials.M_Details}
            />
            <mesh
              name="casette_base_low010_M_Details_Translucent_0"
              geometry={
                nodes.casette_base_low010_M_Details_Translucent_0.geometry
              }
              material={materials.M_Details_Translucent}
            />
          </group>
          <group
            name="casette_base_low011"
            position={[5.834, 0.932, 1.818]}
            rotation={[-Math.PI, -0.813, -Math.PI / 2]}
            scale={[1.054, 0.955, 0.996]}
          >
            <mesh
              name="casette_base_low011_M_Details_0"
              geometry={nodes.casette_base_low011_M_Details_0.geometry}
              material={materials.M_Details}
            />
            <mesh
              name="casette_base_low011_M_Details_Translucent_0"
              geometry={
                nodes.casette_base_low011_M_Details_Translucent_0.geometry
              }
              material={materials.M_Details_Translucent}
            />
          </group>
          <group
            name="casette_base_low012"
            position={[13.58, 0.013, 8.036]}
            rotation={[0.037, 0.62, 1.549]}
          >
            <mesh
              name="casette_base_low012_M_Details_0"
              geometry={nodes.casette_base_low012_M_Details_0.geometry}
              material={materials.M_Details}
              position={[-0.528, 21.739, -17.396]}
            />
            <mesh
              name="casette_base_low012_M_Details_Translucent_0"
              geometry={
                nodes.casette_base_low012_M_Details_Translucent_0.geometry
              }
              material={materials.M_Details_Translucent}
              position={[-0.528, 21.739, -17.396]}
            />
          </group>
          <group
            name="tape_base_low003"
            position={[-10.928, 0.003, 5.67]}
            rotation={[-0.059, -0.464, 1.554]}
          >
            <mesh
              name="tape_base_low003_M_Details_0"
              geometry={nodes.tape_base_low003_M_Details_0.geometry}
              material={materials.M_Details}
              position={[0.387, 11.747, -8.438]}
            />
          </group>
          <group
            name="tape_base_low005"
            position={[-10.205, 0.174, 4.237]}
            rotation={[3.017, -0.052, 1.602]}
          >
            <mesh
              name="tape_base_low005_M_Details_0"
              geometry={nodes.tape_base_low005_M_Details_0.geometry}
              material={materials.M_Details}
              position={[-1.308, 6.092, 13.058]}
            />
          </group>
          <mesh
            name="casette_base_low005_M_Details_Translucent_0"
            geometry={
              nodes.casette_base_low005_M_Details_Translucent_0.geometry
            }
            material={materials.M_Details_Translucent}
            position={[-0.42, 12.292, -3.225]}
            rotation={[-3.139, 0.12, -1.574]}
          />
          <mesh
            name="casette_base_low006_M_Details_Translucent_0"
            geometry={
              nodes.casette_base_low006_M_Details_Translucent_0.geometry
            }
            material={materials.M_Details_Translucent}
            position={[14.499, 0.881, 1.785]}
            rotation={[1.485, 0.169, 0.474]}
          />
          <mesh
            name="casette_base_low007_M_Details_Translucent_0"
            geometry={
              nodes.casette_base_low007_M_Details_Translucent_0.geometry
            }
            material={materials.M_Details_Translucent}
            position={[-1.049, 13.008, -3.657]}
            rotation={[-3.139, -0.2, -1.573]}
          />
          <mesh
            name="casette_lid_low002_M_Details_0"
            geometry={nodes.casette_lid_low002_M_Details_0.geometry}
            material={materials.M_Details}
            position={[-0.267, 11.93, -4.482]}
            rotation={[-3.139, 0.12, -1.574]}
          />
          <mesh
            name="casette_lid_low003_M_Details_0"
            geometry={nodes.casette_lid_low003_M_Details_0.geometry}
            material={materials.M_Details}
            position={[14.392, -0.43, 1.731]}
            rotation={[1.485, 0.169, 0.474]}
          />
          <mesh
            name="casette_lid_low004_M_Details_0"
            geometry={nodes.casette_lid_low004_M_Details_0.geometry}
            material={materials.M_Details}
            position={[-1.299, 12.646, -4.898]}
            rotation={[-3.139, -0.2, -1.573]}
          />
          <mesh
            name="ductTape_low_M_Details_0"
            geometry={nodes.ductTape_low_M_Details_0.geometry}
            material={materials.M_Details}
            position={[0.171, 0.208, -15.174]}
            rotation={[3.094, -0.031, -0.009]}
          />
          <mesh
            name="ductTape_low001_M_Details_0"
            geometry={nodes.ductTape_low001_M_Details_0.geometry}
            material={materials.M_Details}
            position={[11.733, 4.474, -3.962]}
            rotation={[0.393, 0.011, -3.088]}
            scale={-0.61}
          />
          <mesh
            name="ductTape_low002_M_Details_0"
            geometry={nodes.ductTape_low002_M_Details_0.geometry}
            material={materials.M_Details}
            position={[12.605, 1.255, -4.737]}
            rotation={[0.998, 0.135, -3.071]}
            scale={-0.61}
          />
          <mesh
            name="kb_base_low001_M_Keyboard_0"
            geometry={nodes.kb_base_low001_M_Keyboard_0.geometry}
            material={materials.M_Keyboard}
            position={[0.04, 0.756, 6.778]}
            rotation={[-Math.PI, 0.126, 0]}
          />
          <mesh
            name="SM_Cables_M_Details_0"
            geometry={nodes.SM_Cables_M_Details_0.geometry}
            material={materials.M_Details}
            position={[12.352, 6.021, -3.062]}
            rotation={[Math.PI / 2, 0, 0.244]}
          />
          <mesh
            name="SM_Keyboard_Lid_M_Keyboard_Translucent_0"
            geometry={nodes.SM_Keyboard_Lid_M_Keyboard_Translucent_0.geometry}
            material={materials.M_Keyboard_Translucent}
            position={[8.402, 2.044, 8.468]}
            rotation={[3.123, 0.126, 0.002]}
          />
          <mesh
            name="SM_Monitor_M_Monitor_0"
            geometry={nodes.SM_Monitor_M_Monitor_0.geometry}
            material={materials.M_Monitor}
            position={[-0.801, 6.601, -3.287]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="SM_Speakers_M_Speakers_0"
            geometry={nodes.SM_Speakers_M_Speakers_0.geometry}
            material={materials.M_Speakers}
            position={[11.809, 2.21, -0.194]}
            rotation={[Math.PI / 2, 0, 0.36]}
            scale={1.271}
          />
          <mesh
            name="strip_low_M_Details_0"
            geometry={nodes.strip_low_M_Details_0.geometry}
            material={materials.M_Details}
            position={[4.159, 0.963, -12.62]}
            rotation={[-2.809, 0.338, 1.019]}
          />
          <mesh
            name="strip_low001_M_Details_0"
            geometry={nodes.strip_low001_M_Details_0.geometry}
            material={materials.M_Details}
            position={[17.863, -0.255, -3.352]}
            rotation={[2.994, -0.539, 0.189]}
          />
          <mesh
            name="strip_low002_M_Details_0"
            geometry={nodes.strip_low002_M_Details_0.geometry}
            material={materials.M_Details}
            position={[16.831, -0.255, -0.237]}
            rotation={[0.433, -1.266, -2.461]}
          />
          <mesh
            name="tape_base_low001_M_Details_0"
            geometry={nodes.tape_base_low001_M_Details_0.geometry}
            material={materials.M_Details}
            position={[-4.459, 12.139, -3.273]}
            rotation={[0.027, -0.935, 0.027]}
          />
          <mesh
            name="tape_base_low004_M_Details_0"
            geometry={nodes.tape_base_low004_M_Details_0.geometry}
            material={materials.M_Details}
            position={[8.176, 1.434, 10.294]}
            rotation={[-Math.PI, -1.434, -1.846]}
          />
          <mesh
            name="tape_base_low006_M_Details_0"
            geometry={nodes.tape_base_low006_M_Details_0.geometry}
            material={materials.M_Details}
            position={[-9.285, 0.877, -1.199]}
            rotation={[1.571, -0.217, -0.06]}
          />
          <mesh
            name="tape_base_low007_M_Details_0"
            geometry={nodes.tape_base_low007_M_Details_0.geometry}
            material={materials.M_Details}
            position={[11.71, 9.947, -0.395]}
            rotation={[-0.023, -0.824, 3.125]}
          />
          <mesh
            name="tape_base_low008_M_Details_0"
            geometry={nodes.tape_base_low008_M_Details_0.geometry}
            material={materials.M_Details}
            position={[-7.233, 0.105, -8.262]}
            rotation={[-3.128, 0, -Math.PI / 2]}
          />
          <mesh
            name="tape_base_low009_M_Details_0"
            geometry={nodes.tape_base_low009_M_Details_0.geometry}
            material={materials.M_Details}
            position={[-7.232, 0.569, -8.32]}
            rotation={[-0.023, -0.079, 1.569]}
          />
          <mesh
            name="tape_base_low010_M_Details_0"
            geometry={nodes.tape_base_low010_M_Details_0.geometry}
            material={materials.M_Details}
            position={[-7.858, -0.387, -7.884]}
            rotation={[1.558, -0.058, -1.414]}
          />
          <mesh
            name="tape_base_low011_M_Details_0"
            geometry={nodes.tape_base_low011_M_Details_0.geometry}
            material={materials.M_Details}
            position={[-7.232, 0.96, -8.33]}
            rotation={[3.121, -0.262, -1.563]}
          />
          <mesh
            name="tape_base_low012_M_Details_0"
            geometry={nodes.tape_base_low012_M_Details_0.geometry}
            material={materials.M_Details}
            position={[14.499, 0.881, 1.785]}
            rotation={[1.485, 0.169, 0.474]}
          />
          <mesh
            name="tape_base_low013_M_Details_0"
            geometry={nodes.tape_base_low013_M_Details_0.geometry}
            material={materials.M_Details}
            position={[-1.049, 13.008, -3.657]}
            rotation={[-3.139, -0.2, -1.573]}
          />
          <mesh
            name="tape_base_low014_M_Details_0"
            geometry={nodes.tape_base_low014_M_Details_0.geometry}
            material={materials.M_Details}
            position={[-0.42, 12.292, -3.225]}
            rotation={[-3.139, 0.12, 1.568]}
          />
        </group>
      </group>
      <group
        name="Sketchfab_model003"
        position={[25.45, 1.325, -3.195]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.426}
      >
        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
          <group
            name="paper2_1"
            position={[0, 0, 1]}
            rotation={[-1.417, 0.761, 2.668]}
          >
            <mesh
              name="Object_7"
              geometry={nodes.Object_7.geometry}
              material={materials.main}
              position={[-1.214, 3.562, 0.263]}
              rotation={[0.088, -0.235, -0.018]}
            />
          </group>
          <group
            name="paper3_2"
            position={[0, 0, -1]}
            rotation={[2.855, 0.401, 0.41]}
          >
            <mesh
              name="Object_10"
              geometry={nodes.Object_10.geometry}
              material={materials.main}
              position={[-0.715, 2.364, -7.619]}
            />
          </group>
          <mesh
            name="Object_4"
            geometry={nodes.Object_4.geometry}
            material={materials.main}
            position={[-15.886, -0.078, 6.382]}
            rotation={[0, 0, 0.706]}
          />
        </group>
      </group>
      <group
        name="Sketchfab_model005"
        position={[20.39, 0.391, 10.476]}
        rotation={[-Math.PI / 2, 0, -0.351]}
        scale={5.607}
      >
        <group
          name="5f20f189beaf4d1db3a112d368e4ad48fbx"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="radio001_low_radio_0"
            geometry={nodes.radio001_low_radio_0.geometry}
            material={materials.radio}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            name="radio002_low_radio_0"
            geometry={nodes.radio002_low_radio_0.geometry}
            material={materials.radio}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            name="radio003_low_radio_0"
            geometry={nodes.radio003_low_radio_0.geometry}
            material={materials.radio}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            name="radio004_low_radio_0"
            geometry={nodes.radio004_low_radio_0.geometry}
            material={materials.radio}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            name="radio005_low_radio_0"
            geometry={nodes.radio005_low_radio_0.geometry}
            material={materials.radio}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            name="radio006_low_radio_0"
            geometry={nodes.radio006_low_radio_0.geometry}
            material={materials.radio}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            name="radio007_low_radio_0"
            geometry={nodes.radio007_low_radio_0.geometry}
            material={materials.radio}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            name="radio008_low_radio_0"
            geometry={nodes.radio008_low_radio_0.geometry}
            material={materials.radio}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            name="radio009_low_radio_0"
            geometry={nodes.radio009_low_radio_0.geometry}
            material={materials.radio}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            name="radio010_low_Glass_0"
            geometry={nodes.radio010_low_Glass_0.geometry}
            material={materials.Glass}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            name="radio_low_radio_0"
            geometry={nodes.radio_low_radio_0.geometry}
            material={materials.radio}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group
        name="Sketchfab_model007"
        rotation={[-Math.PI / 2, 0, -1.576]}
        scale={5.705}
      >
        <group
          name="a6e54eb81fb44d27967dcc66046b54dcfbx"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Cube003__0"
            geometry={nodes.Cube003__0.geometry}
            material={materials["Scene_-_Root"]}
            position={[-12.479, -4.364, -14.081]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[259.834, 414.12, 259.834]}
          />
        </group>
      </group>
      <mesh
        name="Object_2"
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}
        position={[20.588, 14.168, -1.865]}
        rotation={[-Math.PI / 2, 0, 0.769]}
        scale={25.917}
      />
    </group>
  );
}

useGLTF.preload("/tablepcssnotex.gltf");
